Release qdes-1.1.0 (#31)
* [DDCI-110] Added "upsert" functionality for vocabulary_service_term records.

* [DDCI-107] Added access restrictions for vocab service functions.

* [DDCI-111] Added background process command.

* [DDCI-109] - vocab service edit delete

* [DDCI-109] - change wording

* Fix refresh script.

* Fix for context issue when fetching VocPrez vocab via click.

* Tidy up vocab service table display.

* [DDCI-125] - added CSV reader for vocab

* [DDCI-125] - removed unused vocab type

* Update `datae_modified` when updating vocab service term.

* Added `remote_csv` vocab service to automated refresh.

* Added link to terms to vocab service refresh message.

* Added info to vocab service terms detail page.

* Added CSV example.

* Create nature-of-relationship

* Create temporal-resolution-ranges.csv

* [DDCI-124] - added vocab auto complete

* Add files via upload

* [DDCI-41] PoC work.

* [DDCI-124] Refactoring `vocabulary_service_term_search`
- Adjusted search query to be case insensitive
- Refactored code for simplicity and readability

* [DDCI-213] - accepted duplicate terms

* [DDCI-41]
- Added new blueprint endpoint for 'secure_vocabulary_search'
- Added new action 'secure_vocabulary_search' to search for secure vocabs
- Updated config for 'point-of-contact'
- Added config values
- Added file upload validation
- Removed unused code

* - Added new secure vocab 'the-party'
- 'get_secure_vocabulary_record_label' will not return the query as the label if it cannot find the secure vocab

* Removed debug logs

* Delete key.key

* Delete test.csv

* [DDCI-213] Added migrations
- Added migration for `allow_duplicate_terms` column on `vocabulary_service` table.

* [DDCI-213] Renamed migration file.

* Added new column 'definition' to table 'vocabulary_service_term'

* Added definition to vocabulary service terms

* Added definition to action 'vocabulary_service_term_search'

* Reutrn default value of None if definition key does not exist for csv vocabs

* Fixed definition key lookup

* Added 'definition' to new property 'title' for 'scheming_vocabulary_service_choices'

* Tidy up vocabulary service list table.

* [DDCI-245] - added context to an action

* [DDCI-193] - added never option to refresh freq

* [DDCI-192] - added new cols for vocab

* [DDCI-192] - modified vocpress logic

* [DDCI-192] - added detection for broader uri changes

* [DDCI-169] - validation of invalid uri for vocab (#17)

* [DDCI-170] - added email notification for invalid vocab uri (#18)

* [DDCI-170] - added email notification for invalid vocab uri

* [DDCI-170] - updated email wording

* Refactored code to use toolkit.config

Co-authored-by: Mark Calvert <mark.calvert@salsadigital.com.au>

* [DDCI-170] - fix refresh issue (#19)

* [DDCI-170] - updated link to use ckan helper (#20)

* Updated email templates to use vocab name instead of internal identifier

* Update email template text for 'vocab_service_invalid_urls'

* Added `application/vnd.ms-excel` to allowed mimetypes

* [DDCI-390] - updated the success message

* fix auth issue when looking up point of contact

* [DDCI-244] - added vocab support for render the tree

* Pinned `cryptography` requirement to 3.3.x

On Mon 8th Feb, 2021 - a new version of the `cryptography` package was released that caused deployment/build issues due to:
```
error: Can not find Rust compiler
```
Since cryptography is a future requirement, the package has been pinned to the last stable version.

* Added new action 'get_vocabulary_service_term'
Updated model methods 'get_by_label_or_uri' & 'get_by_uri' to be case insensitive

* [DDCI-74] - added alternative display for search

* [DDCI-482] Fixed `get_remote_csv_vocabulary_terms` action call.

* [DDCI-634] Change secure CSV title

* [DDCI-696] Fix for secure vocab search
- Allow sysadmins without any organisation roles to access `secure_vocabulary_search` get action
- Replaced use of `c.user` and `c.userobj` with `toolkit.g` equivalents

* [DDCI-660] - added octet when upload csv on windows

* [DDCI-685] - updated email wording

* Added job worker title for Vocabulary service update

* Updated 'vocabulary_service_term_table' column 'definition' to be nullable

* Add Email to the search fields (#29)

* Search on uri and term for vocab services (#15)

Added search for 'Email' in secure vocabs

Co-authored-by: Mark Calvert <mark.calvert@salsadigital.com.au>

* [DDCI-260] Replace VocPrez with SPARQL+JSON (#30)

* Replace VocPrez with SPARQL+JSON

* Remove CSIRO service

* Change vocprez mentions to SPARQL_JSON

* Remove breakpoint

* Added check for environment variable 'DISABLE_CRON_JOB_EMAILS' to not send email notification

Co-authored-by: Nathan Perry <nathan@salsadigital.com.au>
Co-authored-by: awang setyawan <awang@salsadigital.com.au>
Co-authored-by: tasjim <jim@salsadigital.com.au>
Co-authored-by: Mark Calvert <mark.calvert@salsadigital.com.au>
Co-authored-by: Konstantin Sivakov <konstantin.sivakov@gmail.com>