Pinned `cryptography` requirement to 3.3.x
On Mon 8th Feb, 2021 - a new version of the `cryptography` package was released that caused deployment/build issues due to:
```
error: Can not find Rust compiler
```
Since cryptography is a future requirement, the package has been pinned to the last stable version.